### ISSUE TITLE
[Question] why recall of Rouge L for pseudo-labels ?

### ISSUE THREAD

**Issue by Colanim** [ChenRocks/fast_abs_rl#41]
I read your paper again, and couldn't find the reason why you are using the recall of ROUGE-L score to make the pseudo-labels. Specifically :

**Why ROUGE-L ? (and not ROUGE-1 for example)**

**Why precision ?**

**Comment by ChenRocks** [comment]
My intuition is Rouge-L correlates better with language fluency and by using recall we can cover more contents in the ground-truth summary. I think you can try Rouge-1 because at least for my model trained on CNN/DM it correlates well with Rouge-L. I do think recall is better than precision and f1 because we want more content to summarize. Nevertheless, feel free to try them out because this is an open question and I might be wrong.

Please also refer to Sec. 3 of the paper and footnote 6, thanks.
