### ISSUE TITLE
run the training in spark cluster

### ISSUE THREAD

**Issue by umangkeshri** [ChenRocks/fast_abs_rl#43]
How can i use this code to train and inference my model in distributed environment of spark cluster which has multiple cpu nodes.

**Comment by ChenRocks** [comment]
Thanks for your interest. Unfortunately, I don't have any experience in spark. From my understanding it is still more efficient to training neural networks on GPU cards. This is a research code base and I don't have plan to extend it to production environment. Closing this issue since it spark support is very unlikely in the foreseeable future.
