### ISSUE TITLE
Possible bug in beam search

### ISSUE THREAD

**Issue by zfang** [ChenRocks/fast_abs_rl#6]
L127-L128 has no effect: https://github.com/ChenRocks/fast_abs_rl/blob/b1b66c180a135905574fdb9e80a6da2cabf7f15c/decoding.py#L126-L130

I assume this is intended:`seq.append(art_sent[max(range(len(art_sent)), key=lambda j: attn[j].item())])`.

**Comment by ChenRocks** [comment]
Good catch! It is indeed a no-op. A quick experiment shows that this doesn't affect the scores much (< 0.01). The UNKs are rare due to the copy-mechanism anyway. I will update code and result tables shortly. Thanks! 

NOTE: This bug appeared *after* we started to refactor the old code base so all original results in our paper is still valid.

**Comment by ChenRocks** [comment]
code and results updated
